apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: coc-pricing-serviceroute
spec:
  hosts:
  - "*"
  gateways:
  - config-gateway
  http:
  - match:
    - uri:
        prefix: /shopping
    route:
    - destination:
        host: coc-pricing-service
        port:
          number: 5556
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: coc-pricing-service
spec:
  hosts:
  - shopping-cartservice
  http:
  - route:
    - destination:
        host: shopping-cartservice
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: coc-pricing-service
spec:
  host: coc-pricing-service
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 1000
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutiveErrors: 7
      interval: 5m
      baseEjectionTime: 15m
      maxEjectionPercent: 100
