apiVersion: v1
kind: ConfigMap
metadata:
    name: shoppingcart-app-configs
data:
  LOGGING_LEVEL_ROOT: INFO
  SERVER_PORT: "8080"
  JAVA_OPTS: "-server -Xms2048m -Xmx2048m -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError"