kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: coc-pricing-service
  #namespace: default TODO: Update the namespace.
  labels:
    run: coc-pricing-service
    app: coc-pricing-service
spec:
  replicas: 1 # TODO: Update the no of replicas
  strategy:
    type: Recreate # TODO: Update the strategy
  template:
    metadata:
      labels:
        run: coc-pricing-service
        app: coc-pricing-service
    spec:
      containers:
        - name: coc-pricing-service
          image: gcr.io/cognitive-genie-63754/coc_coc-pricing-service:latest # TODO: Change the image url
          imagePullPolicy: Always # TODO: Change it to IfNotPresent once CD setup done on cloud
          ports:
            - containerPort: 12789
          env:
          - name: eureka_instance_hostname
            value: 'pricingservice'
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          securityContext:
            privileged: false
#          envFrom:
#            - configMapRef:
#                name: coc-config            
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      imagePullSecrets:
        - name: acr-coc            
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: coc-pricing-service
  #namespace: default #TODO: Make the namespace parameterized.
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: coc-pricing-service
  minReplicas: 1 # TODO: Update the no of minReplicas
  maxReplicas: 1 # TODO: Update the no of maxReplicas
  targetCPUUtilizationPercentage: 80
