kind: Service
apiVersion: v1
metadata:
  name: coc-pricing-service
  #namespace: default #TODO: Make the namespace parameterized.
  labels:
    app: coc-pricing-service
spec:
  ports:
    - name: app-port
      protocol: TCP
      port: 12789
      targetPort: 12789
  selector:
    app: coc-pricing-service
  type: NodePort # TODO: Change it to NodePort on cloud
  sessionAffinity: None
  externalTrafficPolicy: Cluster   
